# used https://github.com/GoogleCloudPlatform/solutions-build-multi-architecture-images-tutorial/blob/master/terraform/cloud-build/build-docker-image-trigger.yaml
# as a guide for the multiarch setup
# (from https://github.com/GoogleCloudPlatform/solutions-build-multi-architecture-images-tutorial)


steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'run', '--privileged', 'linuxkit/binfmt:v0.8' ]
    id: 'initialize-qemu'
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'buildx', 'create', '--name', 'mybuilder' ]
    id: 'create-builder'
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'buildx', 'use', 'mybuilder' ]
    id: 'select-builder'
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'buildx', 'inspect', '--bootstrap' ]
    id: 'show-target-build-platforms'
  - name: 'gcr.io/cloud-builders/docker'
    args: [
        'buildx', 'build',
        '--push',
        '--file', 'Dockerfile-$_OS',
        #'--platform', 'linux/amd64,linux/arm64',
        # remi doesn't support arm64 for centos8, but does for 9
        '--platform', '$_PLATFORMS',
        '-t', 'gcr.io/$PROJECT_ID/$_OS:$BRANCH_NAME',
        '.'
    ]
options:
  env:
    - 'DOCKER_CLI_EXPERIMENTAL=enabled'

  # https://cloud.google.com/cloud-build/docs/api/reference/rest/v1/projects.builds#machinetype
  # unspecified, N1_HIGHCPU_8, N1_HIGHCPU_32, E2_HIGHCPU_8, E2_HIGHCPU_32
  machineType: 'E2_HIGHCPU_32'
timeout: 2400s
